INSERT INTO flags(name, code, path) VALUES('Afghanistan','af','flags/af.svg');
INSERT INTO flags(name, code, path) VALUES('Aland Islands','ax','flags/ax.svg');
INSERT INTO flags(name, code, path) VALUES('Albania','al','flags/al.svg');
INSERT INTO flags(name, code, path) VALUES('Algeria','dz','flags/dz.svg');
INSERT INTO flags(name, code, path) VALUES('American Samoa','as','flags/as.svg');
INSERT INTO flags(name, code, path) VALUES('Andorra','ad','flags/ad.svg');
INSERT INTO flags(name, code, path) VALUES('Angola','ao','flags/ao.svg');
INSERT INTO flags(name, code, path) VALUES('Anguilla','ai','flags/ai.svg');
INSERT INTO flags(name, code, path) VALUES('Antarctica','aq','flags/aq.svg');
INSERT INTO flags(name, code, path) VALUES('Antigua and Barbuda','ag','flags/ag.svg');
INSERT INTO flags(name, code, path) VALUES('Argentina','ar','flags/ar.svg');
INSERT INTO flags(name, code, path) VALUES('Armenia','am','flags/am.svg');
INSERT INTO flags(name, code, path) VALUES('Aruba','aw','flags/aw.svg');
INSERT INTO flags(name, code, path) VALUES('Ascension Island','ac','flags/ac.svg');
INSERT INTO flags(name, code, path) VALUES('Australia','au','flags/au.svg');
INSERT INTO flags(name, code, path) VALUES('Austria','at','flags/at.svg');
INSERT INTO flags(name, code, path) VALUES('Azerbaijan','az','flags/az.svg');
INSERT INTO flags(name, code, path) VALUES('Bahamas','bs','flags/bs.svg');
INSERT INTO flags(name, code, path) VALUES('Bahrain','bh','flags/bh.svg');
INSERT INTO flags(name, code, path) VALUES('Bangladesh','bd','flags/bd.svg');
INSERT INTO flags(name, code, path) VALUES('Barbados','bb','flags/bb.svg');
INSERT INTO flags(name, code, path) VALUES('Basque Country','es-pv','flags/es-pv.svg');
INSERT INTO flags(name, code, path) VALUES('Belarus','by','flags/by.svg');
INSERT INTO flags(name, code, path) VALUES('Belgium','be','flags/be.svg');
INSERT INTO flags(name, code, path) VALUES('Belize','bz','flags/bz.svg');
INSERT INTO flags(name, code, path) VALUES('Benin','bj','flags/bj.svg');
INSERT INTO flags(name, code, path) VALUES('Bermuda','bm','flags/bm.svg');
INSERT INTO flags(name, code, path) VALUES('Bhutan','bt','flags/bt.svg');
INSERT INTO flags(name, code, path) VALUES('Bolivia','bo','flags/bo.svg');
INSERT INTO flags(name, code, path) VALUES('Bonaire, Sint Eustatius and Saba','bq','flags/bq.svg');
INSERT INTO flags(name, code, path) VALUES('Bosnia and Herzegovina','ba','flags/ba.svg');
INSERT INTO flags(name, code, path) VALUES('Botswana','bw','flags/bw.svg');
INSERT INTO flags(name, code, path) VALUES('Bouvet Island','bv','flags/bv.svg');
INSERT INTO flags(name, code, path) VALUES('Brazil','br','flags/br.svg');
INSERT INTO flags(name, code, path) VALUES('British Indian Ocean Territory','io','flags/io.svg');
INSERT INTO flags(name, code, path) VALUES('Brunei Darussalam','bn','flags/bn.svg');
INSERT INTO flags(name, code, path) VALUES('Bulgaria','bg','flags/bg.svg');
INSERT INTO flags(name, code, path) VALUES('Burkina Faso','bf','flags/bf.svg');
INSERT INTO flags(name, code, path) VALUES('Burundi','bi','flags/bi.svg');
INSERT INTO flags(name, code, path) VALUES('Cabo Verde','cv','flags/cv.svg');
INSERT INTO flags(name, code, path) VALUES('Cambodia','kh','flags/kh.svg');
INSERT INTO flags(name, code, path) VALUES('Cameroon','cm','flags/cm.svg');
INSERT INTO flags(name, code, path) VALUES('Canada','ca','flags/ca.svg');
INSERT INTO flags(name, code, path) VALUES('Canary Islands','ic','flags/ic.svg');
INSERT INTO flags(name, code, path) VALUES('Catalonia','es-ct','flags/es-ct.svg');
INSERT INTO flags(name, code, path) VALUES('Cayman Islands','ky','flags/ky.svg');
INSERT INTO flags(name, code, path) VALUES('Central African Republic','cf','flags/cf.svg');
INSERT INTO flags(name, code, path) VALUES('Central European Free Trade Agreement','cefta','flags/cefta.svg');
INSERT INTO flags(name, code, path) VALUES('Chad','td','flags/td.svg');
INSERT INTO flags(name, code, path) VALUES('Chile','cl','flags/cl.svg');
INSERT INTO flags(name, code, path) VALUES('China','cn','flags/cn.svg');
INSERT INTO flags(name, code, path) VALUES('Christmas Island','cx','flags/cx.svg');
INSERT INTO flags(name, code, path) VALUES('Clipperton Island','cp','flags/cp.svg');
INSERT INTO flags(name, code, path) VALUES('Cocos (Keeling) Islands','cc','flags/cc.svg');
INSERT INTO flags(name, code, path) VALUES('Colombia','co','flags/co.svg');
INSERT INTO flags(name, code, path) VALUES('Comoros','km','flags/km.svg');
INSERT INTO flags(name, code, path) VALUES('Cook Islands','ck','flags/ck.svg');
INSERT INTO flags(name, code, path) VALUES('Costa Rica','cr','flags/cr.svg');
INSERT INTO flags(name, code, path) VALUES('Croatia','hr','flags/hr.svg');
INSERT INTO flags(name, code, path) VALUES('Cuba','cu','flags/cu.svg');
INSERT INTO flags(name, code, path) VALUES('Curaçao','cw','flags/cw.svg');
INSERT INTO flags(name, code, path) VALUES('Cyprus','cy','flags/cy.svg');
INSERT INTO flags(name, code, path) VALUES('Czech Republic','cz','flags/cz.svg');
INSERT INTO flags(name, code, path) VALUES('Côte d'Ivoire','ci','flags/ci.svg');
INSERT INTO flags(name, code, path) VALUES('Democratic Republic of the Congo','cd','flags/cd.svg');
INSERT INTO flags(name, code, path) VALUES('Denmark','dk','flags/dk.svg');
INSERT INTO flags(name, code, path) VALUES('Diego Garcia','dg','flags/dg.svg');
INSERT INTO flags(name, code, path) VALUES('Djibouti','dj','flags/dj.svg');
INSERT INTO flags(name, code, path) VALUES('Dominica','dm','flags/dm.svg');
INSERT INTO flags(name, code, path) VALUES('Dominican Republic','do','flags/do.svg');
INSERT INTO flags(name, code, path) VALUES('East African Community','eac','flags/eac.svg');
INSERT INTO flags(name, code, path) VALUES('Ecuador','ec','flags/ec.svg');
INSERT INTO flags(name, code, path) VALUES('Egypt','eg','flags/eg.svg');
INSERT INTO flags(name, code, path) VALUES('El Salvador','sv','flags/sv.svg');
INSERT INTO flags(name, code, path) VALUES('England','gb-eng','flags/gb-eng.svg');
INSERT INTO flags(name, code, path) VALUES('Equatorial Guinea','gq','flags/gq.svg');
INSERT INTO flags(name, code, path) VALUES('Eritrea','er','flags/er.svg');
INSERT INTO flags(name, code, path) VALUES('Estonia','ee','flags/ee.svg');
INSERT INTO flags(name, code, path) VALUES('Eswatini','sz','flags/sz.svg');
INSERT INTO flags(name, code, path) VALUES('Ethiopia','et','flags/et.svg');
INSERT INTO flags(name, code, path) VALUES('Europe','eu','flags/eu.svg');
INSERT INTO flags(name, code, path) VALUES('Falkland Islands','fk','flags/fk.svg');
INSERT INTO flags(name, code, path) VALUES('Faroe Islands','fo','flags/fo.svg');
INSERT INTO flags(name, code, path) VALUES('Federated States of Micronesia','fm','flags/fm.svg');
INSERT INTO flags(name, code, path) VALUES('Fiji','fj','flags/fj.svg');
INSERT INTO flags(name, code, path) VALUES('Finland','fi','flags/fi.svg');
INSERT INTO flags(name, code, path) VALUES('France','fr','flags/fr.svg');
INSERT INTO flags(name, code, path) VALUES('French Guiana','gf','flags/gf.svg');
INSERT INTO flags(name, code, path) VALUES('French Polynesia','pf','flags/pf.svg');
INSERT INTO flags(name, code, path) VALUES('French Southern Territories','tf','flags/tf.svg');
INSERT INTO flags(name, code, path) VALUES('Gabon','ga','flags/ga.svg');
INSERT INTO flags(name, code, path) VALUES('Galicia','es-ga','flags/es-ga.svg');
INSERT INTO flags(name, code, path) VALUES('Gambia','gm','flags/gm.svg');
INSERT INTO flags(name, code, path) VALUES('Georgia','ge','flags/ge.svg');
INSERT INTO flags(name, code, path) VALUES('Germany','de','flags/de.svg');
INSERT INTO flags(name, code, path) VALUES('Ghana','gh','flags/gh.svg');
INSERT INTO flags(name, code, path) VALUES('Gibraltar','gi','flags/gi.svg');
INSERT INTO flags(name, code, path) VALUES('Greece','gr','flags/gr.svg');
INSERT INTO flags(name, code, path) VALUES('Greenland','gl','flags/gl.svg');
INSERT INTO flags(name, code, path) VALUES('Grenada','gd','flags/gd.svg');
INSERT INTO flags(name, code, path) VALUES('Guadeloupe','gp','flags/gp.svg');
INSERT INTO flags(name, code, path) VALUES('Guam','gu','flags/gu.svg');
INSERT INTO flags(name, code, path) VALUES('Guatemala','gt','flags/gt.svg');
INSERT INTO flags(name, code, path) VALUES('Guernsey','gg','flags/gg.svg');
INSERT INTO flags(name, code, path) VALUES('Guinea','gn','flags/gn.svg');
INSERT INTO flags(name, code, path) VALUES('Guinea-Bissau','gw','flags/gw.svg');
INSERT INTO flags(name, code, path) VALUES('Guyana','gy','flags/gy.svg');
INSERT INTO flags(name, code, path) VALUES('Haiti','ht','flags/ht.svg');
INSERT INTO flags(name, code, path) VALUES('Heard Island and McDonald Islands','hm','flags/hm.svg');
INSERT INTO flags(name, code, path) VALUES('Holy See','va','flags/va.svg');
INSERT INTO flags(name, code, path) VALUES('Honduras','hn','flags/hn.svg');
INSERT INTO flags(name, code, path) VALUES('Hong Kong','hk','flags/hk.svg');
INSERT INTO flags(name, code, path) VALUES('Hungary','hu','flags/hu.svg');
INSERT INTO flags(name, code, path) VALUES('Iceland','is','flags/is.svg');
INSERT INTO flags(name, code, path) VALUES('India','in','flags/in.svg');
INSERT INTO flags(name, code, path) VALUES('Indonesia','id','flags/id.svg');
INSERT INTO flags(name, code, path) VALUES('Iran','ir','flags/ir.svg');
INSERT INTO flags(name, code, path) VALUES('Iraq','iq','flags/iq.svg');
INSERT INTO flags(name, code, path) VALUES('Ireland','ie','flags/ie.svg');
INSERT INTO flags(name, code, path) VALUES('Isle of Man','im','flags/im.svg');
INSERT INTO flags(name, code, path) VALUES('Israel','il','flags/il.svg');
INSERT INTO flags(name, code, path) VALUES('Italy','it','flags/it.svg');
INSERT INTO flags(name, code, path) VALUES('Jamaica','jm','flags/jm.svg');
INSERT INTO flags(name, code, path) VALUES('Japan','jp','flags/jp.svg');
INSERT INTO flags(name, code, path) VALUES('Jersey','je','flags/je.svg');
INSERT INTO flags(name, code, path) VALUES('Jordan','jo','flags/jo.svg');
INSERT INTO flags(name, code, path) VALUES('Kazakhstan','kz','flags/kz.svg');
INSERT INTO flags(name, code, path) VALUES('Kenya','ke','flags/ke.svg');
INSERT INTO flags(name, code, path) VALUES('Kiribati','ki','flags/ki.svg');
INSERT INTO flags(name, code, path) VALUES('Kosovo','xk','flags/xk.svg');
INSERT INTO flags(name, code, path) VALUES('Kuwait','kw','flags/kw.svg');
INSERT INTO flags(name, code, path) VALUES('Kyrgyzstan','kg','flags/kg.svg');
INSERT INTO flags(name, code, path) VALUES('Laos','la','flags/la.svg');
INSERT INTO flags(name, code, path) VALUES('Latvia','lv','flags/lv.svg');
INSERT INTO flags(name, code, path) VALUES('League of Arab States','arab','flags/arab.svg');
INSERT INTO flags(name, code, path) VALUES('Lebanon','lb','flags/lb.svg');
INSERT INTO flags(name, code, path) VALUES('Lesotho','ls','flags/ls.svg');
INSERT INTO flags(name, code, path) VALUES('Liberia','lr','flags/lr.svg');
INSERT INTO flags(name, code, path) VALUES('Libya','ly','flags/ly.svg');
INSERT INTO flags(name, code, path) VALUES('Liechtenstein','li','flags/li.svg');
INSERT INTO flags(name, code, path) VALUES('Lithuania','lt','flags/lt.svg');
INSERT INTO flags(name, code, path) VALUES('Luxembourg','lu','flags/lu.svg');
INSERT INTO flags(name, code, path) VALUES('Macau','mo','flags/mo.svg');
INSERT INTO flags(name, code, path) VALUES('Madagascar','mg','flags/mg.svg');
INSERT INTO flags(name, code, path) VALUES('Malawi','mw','flags/mw.svg');
INSERT INTO flags(name, code, path) VALUES('Malaysia','my','flags/my.svg');
INSERT INTO flags(name, code, path) VALUES('Maldives','mv','flags/mv.svg');
INSERT INTO flags(name, code, path) VALUES('Mali','ml','flags/ml.svg');
INSERT INTO flags(name, code, path) VALUES('Malta','mt','flags/mt.svg');
INSERT INTO flags(name, code, path) VALUES('Marshall Islands','mh','flags/mh.svg');
INSERT INTO flags(name, code, path) VALUES('Martinique','mq','flags/mq.svg');
INSERT INTO flags(name, code, path) VALUES('Mauritania','mr','flags/mr.svg');
INSERT INTO flags(name, code, path) VALUES('Mauritius','mu','flags/mu.svg');
INSERT INTO flags(name, code, path) VALUES('Mayotte','yt','flags/yt.svg');
INSERT INTO flags(name, code, path) VALUES('Mexico','mx','flags/mx.svg');
INSERT INTO flags(name, code, path) VALUES('Moldova','md','flags/md.svg');
INSERT INTO flags(name, code, path) VALUES('Monaco','mc','flags/mc.svg');
INSERT INTO flags(name, code, path) VALUES('Mongolia','mn','flags/mn.svg');
INSERT INTO flags(name, code, path) VALUES('Montenegro','me','flags/me.svg');
INSERT INTO flags(name, code, path) VALUES('Montserrat','ms','flags/ms.svg');
INSERT INTO flags(name, code, path) VALUES('Morocco','ma','flags/ma.svg');
INSERT INTO flags(name, code, path) VALUES('Mozambique','mz','flags/mz.svg');
INSERT INTO flags(name, code, path) VALUES('Myanmar','mm','flags/mm.svg');
INSERT INTO flags(name, code, path) VALUES('Namibia','na','flags/na.svg');
INSERT INTO flags(name, code, path) VALUES('Nauru','nr','flags/nr.svg');
INSERT INTO flags(name, code, path) VALUES('Nepal','np','flags/np.svg');
INSERT INTO flags(name, code, path) VALUES('Netherlands','nl','flags/nl.svg');
INSERT INTO flags(name, code, path) VALUES('New Caledonia','nc','flags/nc.svg');
INSERT INTO flags(name, code, path) VALUES('New Zealand','nz','flags/nz.svg');
INSERT INTO flags(name, code, path) VALUES('Nicaragua','ni','flags/ni.svg');
INSERT INTO flags(name, code, path) VALUES('Niger','ne','flags/ne.svg');
INSERT INTO flags(name, code, path) VALUES('Nigeria','ng','flags/ng.svg');
INSERT INTO flags(name, code, path) VALUES('Niue','nu','flags/nu.svg');
INSERT INTO flags(name, code, path) VALUES('Norfolk Island','nf','flags/nf.svg');
INSERT INTO flags(name, code, path) VALUES('North Korea','kp','flags/kp.svg');
INSERT INTO flags(name, code, path) VALUES('North Macedonia','mk','flags/mk.svg');
INSERT INTO flags(name, code, path) VALUES('Northern Ireland','gb-nir','flags/gb-nir.svg');
INSERT INTO flags(name, code, path) VALUES('Northern Mariana Islands','mp','flags/mp.svg');
INSERT INTO flags(name, code, path) VALUES('Norway','no','flags/no.svg');
INSERT INTO flags(name, code, path) VALUES('Oman','om','flags/om.svg');
INSERT INTO flags(name, code, path) VALUES('Pakistan','pk','flags/pk.svg');
INSERT INTO flags(name, code, path) VALUES('Palau','pw','flags/pw.svg');
INSERT INTO flags(name, code, path) VALUES('Panama','pa','flags/pa.svg');
INSERT INTO flags(name, code, path) VALUES('Papua New Guinea','pg','flags/pg.svg');
INSERT INTO flags(name, code, path) VALUES('Paraguay','py','flags/py.svg');
INSERT INTO flags(name, code, path) VALUES('Peru','pe','flags/pe.svg');
INSERT INTO flags(name, code, path) VALUES('Philippines','ph','flags/ph.svg');
INSERT INTO flags(name, code, path) VALUES('Pitcairn','pn','flags/pn.svg');
INSERT INTO flags(name, code, path) VALUES('Poland','pl','flags/pl.svg');
INSERT INTO flags(name, code, path) VALUES('Portugal','pt','flags/pt.svg');
INSERT INTO flags(name, code, path) VALUES('Puerto Rico','pr','flags/pr.svg');
INSERT INTO flags(name, code, path) VALUES('Qatar','qa','flags/qa.svg');
INSERT INTO flags(name, code, path) VALUES('Republic of the Congo','cg','flags/cg.svg');
INSERT INTO flags(name, code, path) VALUES('Romania','ro','flags/ro.svg');
INSERT INTO flags(name, code, path) VALUES('Russia','ru','flags/ru.svg');
INSERT INTO flags(name, code, path) VALUES('Rwanda','rw','flags/rw.svg');
INSERT INTO flags(name, code, path) VALUES('Réunion','re','flags/re.svg');
INSERT INTO flags(name, code, path) VALUES('Saint Barthélemy','bl','flags/bl.svg');
INSERT INTO flags(name, code, path) VALUES('Saint Helena, Ascension and Tristan da Cunha','sh','flags/sh.svg');
INSERT INTO flags(name, code, path) VALUES('Saint Kitts and Nevis','kn','flags/kn.svg');
INSERT INTO flags(name, code, path) VALUES('Saint Lucia','lc','flags/lc.svg');
INSERT INTO flags(name, code, path) VALUES('Saint Martin','mf','flags/mf.svg');
INSERT INTO flags(name, code, path) VALUES('Saint Pierre and Miquelon','pm','flags/pm.svg');
INSERT INTO flags(name, code, path) VALUES('Saint Vincent and the Grenadines','vc','flags/vc.svg');
INSERT INTO flags(name, code, path) VALUES('Samoa','ws','flags/ws.svg');
INSERT INTO flags(name, code, path) VALUES('San Marino','sm','flags/sm.svg');
INSERT INTO flags(name, code, path) VALUES('Sao Tome and Principe','st','flags/st.svg');
INSERT INTO flags(name, code, path) VALUES('Saudi Arabia','sa','flags/sa.svg');
INSERT INTO flags(name, code, path) VALUES('Scotland','gb-sct','flags/gb-sct.svg');
INSERT INTO flags(name, code, path) VALUES('Senegal','sn','flags/sn.svg');
INSERT INTO flags(name, code, path) VALUES('Serbia','rs','flags/rs.svg');
INSERT INTO flags(name, code, path) VALUES('Seychelles','sc','flags/sc.svg');
INSERT INTO flags(name, code, path) VALUES('Sierra Leone','sl','flags/sl.svg');
INSERT INTO flags(name, code, path) VALUES('Singapore','sg','flags/sg.svg');
INSERT INTO flags(name, code, path) VALUES('Sint Maarten','sx','flags/sx.svg');
INSERT INTO flags(name, code, path) VALUES('Slovakia','sk','flags/sk.svg');
INSERT INTO flags(name, code, path) VALUES('Slovenia','si','flags/si.svg');
INSERT INTO flags(name, code, path) VALUES('Solomon Islands','sb','flags/sb.svg');
INSERT INTO flags(name, code, path) VALUES('Somalia','so','flags/so.svg');
INSERT INTO flags(name, code, path) VALUES('South Africa','za','flags/za.svg');
INSERT INTO flags(name, code, path) VALUES('South Georgia and the South Sandwich Islands','gs','flags/gs.svg');
INSERT INTO flags(name, code, path) VALUES('South Korea','kr','flags/kr.svg');
INSERT INTO flags(name, code, path) VALUES('South Sudan','ss','flags/ss.svg');
INSERT INTO flags(name, code, path) VALUES('Spain','es','flags/es.svg');
INSERT INTO flags(name, code, path) VALUES('Sri Lanka','lk','flags/lk.svg');
INSERT INTO flags(name, code, path) VALUES('State of Palestine','ps','flags/ps.svg');
INSERT INTO flags(name, code, path) VALUES('Sudan','sd','flags/sd.svg');
INSERT INTO flags(name, code, path) VALUES('Suriname','sr','flags/sr.svg');
INSERT INTO flags(name, code, path) VALUES('Svalbard and Jan Mayen','sj','flags/sj.svg');
INSERT INTO flags(name, code, path) VALUES('Sweden','se','flags/se.svg');
INSERT INTO flags(name, code, path) VALUES('Switzerland','ch','flags/ch.svg');
INSERT INTO flags(name, code, path) VALUES('Syria','sy','flags/sy.svg');
INSERT INTO flags(name, code, path) VALUES('Taiwan','tw','flags/tw.svg');
INSERT INTO flags(name, code, path) VALUES('Tajikistan','tj','flags/tj.svg');
INSERT INTO flags(name, code, path) VALUES('Tanzania','tz','flags/tz.svg');
INSERT INTO flags(name, code, path) VALUES('Thailand','th','flags/th.svg');
INSERT INTO flags(name, code, path) VALUES('Timor-Leste','tl','flags/tl.svg');
INSERT INTO flags(name, code, path) VALUES('Togo','tg','flags/tg.svg');
INSERT INTO flags(name, code, path) VALUES('Tokelau','tk','flags/tk.svg');
INSERT INTO flags(name, code, path) VALUES('Tonga','to','flags/to.svg');
INSERT INTO flags(name, code, path) VALUES('Trinidad and Tobago','tt','flags/tt.svg');
INSERT INTO flags(name, code, path) VALUES('Tristan da Cunha','ta','flags/ta.svg');
INSERT INTO flags(name, code, path) VALUES('Tunisia','tn','flags/tn.svg');
INSERT INTO flags(name, code, path) VALUES('Turkmenistan','tm','flags/tm.svg');
INSERT INTO flags(name, code, path) VALUES('Turks and Caicos Islands','tc','flags/tc.svg');
INSERT INTO flags(name, code, path) VALUES('Tuvalu','tv','flags/tv.svg');
INSERT INTO flags(name, code, path) VALUES('Türkiye','tr','flags/tr.svg');
INSERT INTO flags(name, code, path) VALUES('Uganda','ug','flags/ug.svg');
INSERT INTO flags(name, code, path) VALUES('Ukraine','ua','flags/ua.svg');
INSERT INTO flags(name, code, path) VALUES('United Arab Emirates','ae','flags/ae.svg');
INSERT INTO flags(name, code, path) VALUES('United Kingdom','gb','flags/gb.svg');
INSERT INTO flags(name, code, path) VALUES('United Nations','un','flags/un.svg');
INSERT INTO flags(name, code, path) VALUES('United States Minor Outlying Islands','um','flags/um.svg');
INSERT INTO flags(name, code, path) VALUES('United States of America','us','flags/us.svg');
INSERT INTO flags(name, code, path) VALUES('Unknown','xx','flags/xx.svg');
INSERT INTO flags(name, code, path) VALUES('Uruguay','uy','flags/uy.svg');
INSERT INTO flags(name, code, path) VALUES('Uzbekistan','uz','flags/uz.svg');
INSERT INTO flags(name, code, path) VALUES('Vanuatu','vu','flags/vu.svg');
INSERT INTO flags(name, code, path) VALUES('Venezuela','ve','flags/ve.svg');
INSERT INTO flags(name, code, path) VALUES('Vietnam','vn','flags/vn.svg');
INSERT INTO flags(name, code, path) VALUES('Virgin Islands (British)','vg','flags/vg.svg');
INSERT INTO flags(name, code, path) VALUES('Virgin Islands (U.S.)','vi','flags/vi.svg');
INSERT INTO flags(name, code, path) VALUES('Wales','gb-wls','flags/gb-wls.svg');
INSERT INTO flags(name, code, path) VALUES('Wallis and Futuna','wf','flags/wf.svg');
INSERT INTO flags(name, code, path) VALUES('Western Sahara','eh','flags/eh.svg');
INSERT INTO flags(name, code, path) VALUES('Yemen','ye','flags/ye.svg');
INSERT INTO flags(name, code, path) VALUES('Zambia','zm','flags/zm.svg');
INSERT INTO flags(name, code, path) VALUES('Zimbabwe','zw','flags/zw.svg');
